services:
  djangoapp:
    container_name: djangoapp
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./:/djangoapp
    env_file:
      - ./docker_dotenv_files/.env
    depends_on:
      - postgresql-sexta
    networks:
      - bridge_network

  postgresql-sexta:
    container_name: postgresql-sexta
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./docker_dotenv_files/.env
    ports:
      - "5432:5432"
    networks:
      - bridge_network

networks:
  bridge_network:
    driver: bridge